server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: AraSimon
    password: testtest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
    drop-first: false

indexing-settings:
  sites:
    - url: https://sendel.ru/
      name: Sendel
    - url: https://nikoartgallery.com/
      name: NikoGallery
    - url: https://dombulgakova.ru/
      name: DomBulgakova

connection-profile:
  userAgent: SearchEngine
  referrer: http://www.google.com